### PR TITLE
Workingonalpha

### PR DESCRIPTION
**Pull request by HAAKS**
Please merge, I've already resolved the conflicts @AhmedZaleh

### CODE REVIEW

**Comment by ghost** [comment]
@HAAKS git pull master and fix conflicts.

**Comment by HAAKS** [comment]
@AhmedZaleh I've already fixed the conflicts

**Comment by ghost** [comment]
@HAAKS 
screenshot from 2015-04-18 15 35 33

**Comment by HAAKS** [comment]
@AhmedZaleh  it seems that the master was updated , anyway, I've resolved the conflicts again but db/schema I've just left the recent and commented the rest, so please check it

**Comment by ghost** [comment]
@HAAKS 
delete this line https://github.com/Biscode/yard/blob/workingonalpha/db/schema.rb#L43

screenshot from 2015-04-18 16 14 57

**Comment by HAAKS** [comment]
@AhmedZaleh  done :)

**Pull request merged**
